# Generated by Django 2.2.12 on 2022-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('dia_creado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
