# Generated by Django 2.2.12 on 2022-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220302_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquina', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(choices=[('Encendida', 'Apagada')], max_length=30, null=True)),
                ('categoria', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('dia_creada', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
