# Generated by Django 2.2.12 on 2022-03-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='nombre_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Usuario'),
        ),
    ]
