# Generated by Django 2.2.12 on 2022-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_maquina_nombre_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nombre_maquina',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
