# Generated by Django 2.2.12 on 2022-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220311_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
