# Generated by Django 2.2.12 on 2022-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alumno_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
