# Generated by Django 2.2.12 on 2022-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220320_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='root_flag',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='user_flag',
        ),
        migrations.AddField(
            model_name='maquina',
            name='profile_image',
            field=models.ImageField(default='foto_perfil.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='maquina',
            name='root_flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='user_flag',
            field=models.IntegerField(null=True),
        ),
    ]
