# Generated by Django 2.2.12 on 2022-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220328_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='root_flag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='user_flag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
