# Generated by Django 2.2.12 on 2022-03-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220328_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='profile_image',
            new_name='image_machine',
        ),
    ]
