# Generated by Django 2.2.12 on 2022-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220328_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesed_date', models.DateTimeField(auto_now_add=True)),
                ('user_flag', models.BooleanField(default=False)),
                ('root_flag', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Alumno')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Maquina')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='accessed_machines',
            field=models.ManyToManyField(through='accounts.Acceso', to='accounts.Maquina'),
        ),
    ]
