# Generated by Django 2.2.12 on 2022-03-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220330_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceso',
            old_name='alumno',
            new_name='alumnoA',
        ),
        migrations.RenameField(
            model_name='acceso',
            old_name='maquina',
            new_name='maquinaA',
        ),
    ]
