# Generated by Django 2.2.12 on 2022-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220330_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='puntos_conseguidos',
            new_name='points',
        ),
    ]
