# Generated by Django 2.2.12 on 2022-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20220402_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='profile_image',
            field=models.ImageField(default='foto_perfil.png', upload_to='images/'),
        ),
    ]
