# Generated by Django 2.2.12 on 2022-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220405_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='image_machine',
            field=models.ImageField(default='linuxLogo.png', upload_to='images/'),
        ),
    ]
