# Generated by Django 2.2.12 on 2022-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20220405_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='openvpnFile',
            field=models.FileField(default='lab_DobleGI.ovpn', upload_to='openvpn/'),
        ),
    ]
