# Generated by Django 2.2.12 on 2022-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alumno_openvpnfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='openvpnFile',
            field=models.FileField(default='openvpn/lab_DobleGI.ovpn', upload_to='openvpn/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='profile_image',
            field=models.ImageField(default='images/foto_perfil.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='image_machine',
            field=models.ImageField(default='images/linuxLogo.png', upload_to='images/'),
        ),
    ]
