# Generated by Django 2.2.12 on 2022-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220406_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='profile_image',
            field=models.ImageField(default='images/profileImages/foto_perfil.png', upload_to='images/profileImages/'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='image_machine',
            field=models.ImageField(default='images/machineImages/linuxLogo.png', upload_to='images/machineImages/'),
        ),
    ]
