# Generated by Django 2.2.12 on 2022-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220406_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='openvpnFile',
            field=models.FileField(default='openvpn/lab_DobleGI.ovpn', null=True, upload_to='openvpn/'),
        ),
    ]
