# Generated by Django 2.2.12 on 2022-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220406_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
