# Generated by Django 2.2.12 on 2022-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220406_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='maquinas_completadas',
            field=models.IntegerField(default=0),
        ),
    ]
