# Generated by Django 2.2.12 on 2022-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220412_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
