# Generated by Django 2.2.12 on 2022-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20220426_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dia_creada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
