# Generated by Django 2.2.12 on 2022-04-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_category_dia_creada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Category'),
        ),
    ]
