# Generated by Django 2.2.12 on 2022-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20220427_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('FA', 'Facil'), ('ME', 'Media'), ('DI', 'Difífil'), ('IN', 'Insana')], max_length=30, null=True),
        ),
    ]
