# Generated by Django 2.2.12 on 2022-04-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220427_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='estado',
            new_name='dificultad',
        ),
    ]
