# Generated by Django 2.2.12 on 2022-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_acceso_finished_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='finished_date',
        ),
        migrations.AddField(
            model_name='acceso',
            name='days_to_finish',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='hours_to_finish',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='minutes_to_finish',
            field=models.IntegerField(null=True),
        ),
    ]
