# Generated by Django 2.2.12 on 2022-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20220501_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='days_to_finish',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='hours_to_finish',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='minutes_to_finish',
            field=models.IntegerField(default=False),
        ),
    ]
