# Generated by Django 2.2.12 on 2022-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20220501_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
