# Generated by Django 2.2.12 on 2022-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_maquina_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='categoria',
        ),
        migrations.AddField(
            model_name='maquina',
            name='categoria',
            field=models.ManyToManyField(to='accounts.Category'),
        ),
    ]
