# Generated by Django 4.0.5 on 2022-07-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20220626_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='position',
        ),
    ]
